### ISSUE TITLE
Shared Logging Architecture

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#13]
We should include some sort of code for logging messages, mostly for debug purposes. It could be set up to write to both the console, and a file, to keep a record of what different programs have been doing. It would also make debugging the programs to be a bit more formalized than throwing in `Console.WriteLine` calls everywhere.

Ideally, going off of existing logger frameworks, different levels of messages should be loggable (and differentiable in the logger output), from the lowest level "Info" to the highest level "Fatal"/"Critical"/whatever. It we make it extensible enough, we could have multiple loggers open at once, to direct different output to different files. This would allow us to have different file for network messages, simulation messages, ect...

**Comment by mossseank** [comment]
[NLog](http://nlog-project.org/) is a good place to start looking at functionality we may want. We could just use NLog, but it is a pretty complex library, and requires some extra configuration files to work properly. It may be better to write our own small Logging system as to not overburden our project with extra required libraries and extraneous code.

**Comment by LesPaul21** [comment]
log4net by Apache may be an option. It offers hierarchical logging and is portable between differing languages and frameworks. I would take a fair amount of studying to learn but would provide a single model for logging.

Note: Depending on how we choose to organize the repo, would need to be careful about log4net making concurrent writes.

**Comment by mossseank** [comment]
I forgot to upload it, but I did run across ![this image](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c3fb0cbe467800139e2fb1/125516c66e82c728ace21e0d46e6918e208a82bb9babf301b44fff9e2c4533317346f67273d6e52dbc147d535c0948a541585d12fafa8879a4e42e6c981e5ab38532022d8c6853beb2901eb60bbb258b4784bfb58b44c4ee3524f5c6.png) in my initial research. I don't expect that we will be at the point where performant logging is important, but we should keep it in mind.

**Comment by LesPaul21** [comment]
I've chosen NLog for our logging system. It's fairly simple and easy to use once you work through the tutorials. I'm working on getting it installed and working on all parts of our system and then we will have to sit down and talk about our logging conventions.

**Comment by LesPaul21** [comment]
I created an External Project to get the NLog  files ready to use as soon as you pull them down. They are installed on all three projects (SimViewer, SimManager, and SimCommon) There are some examples in the config files for your reference. Below is an excellent tutorial on how to use it. This is ready to merge.

https://github.com/NLog/NLog/wiki/Tutorial
