### ISSUE TITLE
Finalize Copyright & Company Info

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#14]
This is a small task and is not particularly important or critical, but .NET assemblies allow embedding of copyright and company ownership information within the assembly IR. It would be nice to figure out what to fill into these parts, and may require input from NG.

**Comment by LesPaul21** [comment]
I contacted Dave and Carol. I'm waiting on them to get back to me with the info. Once they do, I'll input it and I'll close out the card.

**Comment by LesPaul21** [comment]
Copyright will be under NG-GameSim team. NG doesn't seem to care about retaining any kind of copyright.

**Comment by mossseank** [comment]
Addition of the copyright and company info into the project has been placed in the purview of #15.
