### ISSUE TITLE
Decide on License for Code

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#15]
Since the project is open source, we need to decide on a license under which to put the code and assets that we use in the project. We will mostly likely need separate licenses for both with code parts, and the asset parts. We may also potentially need a different license for the dummy algorithms we write.

One potential thing to worry about is that the license we apply to the dummy algorithms will probably also apply to any algorithms that are written for the competition. This includes any algorithms that NG writes and gives to us. Because of this, we may need NG input on this ticket as well.

**Comment by LesPaul21** [comment]
Creative commons for 3D Models.

**Comment by LesPaul21** [comment]
GPL3 for Source Code

**Comment by mossseank** [comment]
We can close this ticket when the license text is added to the repo, and the README properly reflects how the licenses apply to the parts of the repo. We should also put the copyright information into the repo, and properly define in the README exactly who the copyright belongs to.
