### ISSUE TITLE
Outline of API Functions

### ISSUE THREAD

**Issue by LesPaul21** [NGGameSim/NGGameSim#23]

**Comment by LesPaul21** [comment]
An idea for our API functions:

SERVER

getPosition()
- Takes no input
- Returns...
    - Current x and y position of friendly tank and UAV
    - Last known x and y position of enemy tank (if any)
    - Field of view of UAV

CLIENT

int moveUAVx(int n)
- Takes the number of units to move in the x direction as input
- Moves UAV n units in the x-direction
- Returns the new x position of the UAV

int moveUAVy (int n)
- Same as moveUAVx() but in the y direction

***Tank would have move functions just like the UAV***

bool fire(int x, int y)
- Takes x and y coordinates to fire on as target
- Returns true if hit, false if miss

bool isDetected(Field of View)
- Takes a UAVs field of view as input
- Returns true if the enemy tank is within the field of view and records that position, returns false otherwise
- ***This could possibly be implemented into getPosition***
   - Every call to getPosition() would inform the algorithm whether or not the tank is 
   detected in the UAVs field of view

**Comment by Moodiment** [comment]
TODO: Add documentation involving API functions to github wiki.

**Comment by Moodiment** [comment]
https://github.com/NGGameSim/NGGameSim/wiki/C%23-API-Functions
URL for the first version of the API functions

**Comment by Moodiment** [comment]
Need to modify the functions now to the velocity/vector based system

**Comment by Moodiment** [comment]
Modification of the functions in the NG-Wikipedia are complete. Awaiting Review.

**Comment by mossseank** [comment]
Closing this for now, since we are reworking it in a slightly different way.
