### ISSUE TITLE
Create Network Managers

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#32]
We should create classes that manage the low level sending and processing of incoming messages, and then delegates out the network packets to be processed by the proper subsystems. These will most likely act as Singleton style classes, since only one is needed on each end. The client and the server will (necessarily) have different managers, but shared data such as opcodes and packet handling could theoretically go into the shared code library.

On the client, the network manager could be structured similarly to the input manager written for #20, and on the server it will probably have to run on a background thread like the current example code is doing.

This ticket can be closed as soon as the classes are written, and the current example code used for networking is moved into these classes, and working identically to before.

**Comment by BookerLightman** [comment]
It works identically as before except that it does not close the server, not sure how necessary it is.
