### ISSUE TITLE
Formalize Documentation Format

### ISSUE THREAD

**Issue by LesPaul21** [NGGameSim/NGGameSim#34]
Create a standardized format for our documentation

**Comment by LesPaul21** [comment]
Heavily considering setting up Doxygen.

**Comment by mossseank** [comment]
Look into the C# standard defined comments on types and functions. Visual Studio makes it super easy to do this by generating stubs if you type three slashes above the thing you want to comment.

**Comment by mossseank** [comment]
We are using the standard C# documentation format. Just type three forward slashes above the block you want to comment, and it will generate a stub for you.
