### ISSUE TITLE
Decide on Algorithm Style

### ISSUE THREAD

**Issue by LesPaul21** [NGGameSim/NGGameSim#36]
Multiple Times Per Second or Chess Style

**Comment by LesPaul21** [comment]
Set three speeds (high, medium, low), you are able to move eight directions (cardinal and diagonal).

**Comment by mossseank** [comment]
We will provide helper functions for checking to see if the entity is in danger of leaving the play area. The entities will be able to set a target speed or direction, and the simulation will handle updating the entity information over time to avoid sharp turns or unrealistic accelerations.
