### ISSUE TITLE
Decide on Algorithm API Style

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#6]
We need to decide how teams will write algorithms, and how our application will support them.

Three primary solutions are available:
1. **File System** - The simulation state is written to a file after every iteration, and the algorithms will read in and parse the state from the file, and then write their commands back to another file.
2. ~~**Embedded Language** - We could embed a scripting language such as Lua or Python in the C# application, and then the algorithms will be loaded at runtime and executed.~~
3. **C# API** - We could write a C# API that the algorithms can use.

We should discuss pros and cons

**Comment by mossseank** [comment]
We discussed in the meeting today that we will need to get more information from NG about how they need the algorithm API to work. There seems to be some confusion about the level to which we need to interface with actual C4ISR algorithms, or if we need to implement a much more simple algorithm API that has very little to do with existing C4ISR.

I removed this ticket from Milestone 1 as the API does not need to come in for at least another milestone. We can still discuss it once we hear from NG, but a final decision probably wont be needed for a few more weeks.

**Comment by Moodiment** [comment]
In short, we have decided to move forward with the C# API idea, dropping the File System I/O. This choice was made because the difficulty of teaching people to use the C# API vs parsing our File system is minimal, and the benefits of using C# API range from speed to nice uniformity.

**Comment by mossseank** [comment]
![Screenshot-2017-10-24 Meeting Notes (Last Update 10 12).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c3fb0cbe467800139e2fb1/125516c66e82c728ace21e0d46db978826878dba87e6ab0ef60da1c36417773e7b50e3067580f721b1453b2f001b1bef51402315bfbd994ee6e26d34df4c0aedc16c5d6dd42103ecfadd45ea52fe32815d80bfef891a95bb3b73e588d949371e051adff95e34f29b19da44e409b01301fb4e6f29b33424765595197f2d6e672ea3f4db55828367adb20262.png)

**Comment by mossseank** [comment]
We are using a C# API.
