### ISSUE TITLE
Update API Page on Wiki

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#62]
We need to update the API page on the wiki with the functions discussed in the 12/5 meeting. We are also adding constants.

**Comment by daltonmcclain** [comment]
API - Function List 
RETURNS FUNCTION NAME(PARAMETERS)
Constants:
	ViewRadius
	BoomRange
 
Position Get{Tank,UAV}Position()
Int Get{Tank,UAV}Speed()
Int Get{Tank,UAV}Heading()
Int GetRemainingMissiles()
 
Position GetLastKnownPosition()
Bool DetectedThisTurn()
 
Void Set{Tank,UAV}Speed(Int TargetSpeed)
Void Set{Tank,UAV}Heading(Int TargetHeading)
 
Bool Fire(TargetPosition)
Bool CanFire()

**Comment by daltonmcclain** [comment]
Descriptions for fire functions, constants, and detection functions.
