### ISSUE TITLE
Small Update Debugging

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#70]
We need to fix the fire logic (magic speed-changing missiles are bad), as well as the position updates (swapping x and y trig). Also any other small debugging issues with the current simulation update code.

**Comment by mossseank** [comment]
We also need to update the UAV detection variables.

**Comment by LesPaul21** [comment]
UAV detection variables now update, x and y trig has been swapped, missiles now change travel time based on distance to target. Still need to interpolate the speed
