### ISSUE TITLE
Fix Missile IPC

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#79]
Right now the IPC only sends a dump of missile information, and which missile the information belongs to cannot be tracked. This will represent a relatively simple addition of some unique identifier to the missile data.

**Comment by LesPaul21** [comment]
Currently missile positions are just being communicated as the targets. We need to find a way to get the live position and calculate the heading

We then need to read that in on the viewer side and draw it with the rest of the entities.

**Comment by LesPaul21** [comment]
The math is solid but somehow missiles are getting deleted before we're sending the packets from server to client. mcount is always 0 on the client side and also 0 right before  we send the packet but if you check updateMissiles() you can see they are getting added

**Comment by Moodiment** [comment]
I have checked and confirmed that Missile IPC is now working fully. Positions generated from the SimManager are translated to SimViewer correctly. HOWEVER the positions generated by SimManager ARE NOT CORRECT. The math needs to be fixed, basically.
