### ISSUE TITLE
Add Missiles to 2D Visualization

### ISSUE THREAD

**Issue by mossseank** [NGGameSim/NGGameSim#80]
When #79 is complete, we will be able to add missiles to the 2D visualization, as they will finally be tracked correctly. Will probably just appear as a black dot about half the size of the entity markers.

**Comment by Moodiment** [comment]
Missiles are being rendered in 2D. However they their positions are not updating correctly. Their math needs to be fixed.

Possible debug solution: Create algorithm that shoots toward center of screen and modify code to match desired missile target state.
