### ISSUE TITLE
Model the Final GUI

### ISSUE THREAD

**Issue by LesPaul21** [NGGameSim/NGGameSim#82]
LesPaul21 commented in a few seconds collaborator
We need to create a model of the final Admin GUI that we will deploy with. This doesn't need to be done on Eto.Forms yet. We just need to get it down on paper so we know what we're building.

**Comment by LesPaul21** [comment]
We need to create a model of the final Admin GUI that we will deploy with. This doesn't need to be done on Eto.Forms yet. We just need to get it down on paper so we know what we're building.

**Comment by mossseank** [comment]
Server View:
![SimManager.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c3fb0cbe467800139e2fb1/125516c66e82c728ace21e0d46db9d970e838da888ecad01e81fe086264c22703d46f96925dce07bb9477857095d4dfa47515f44feaf8f28a7e43e22984019af80330b2b9b645bf9fa9015ad03b82a8a4a84beb88f4ec9e93a2cee8a9d02.png)

Client View:
![SimViewer.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c3fb0cbe467800139e2fb1/125516c66e82c728ace21e0d46db9d97158b86be8afbfd0fe64de29b234324676b5ee17e2986b02eba412d075d5c18aa48585f46aaff8a2af4b46e62964e49bc8f3900299f7744eeaa880dbe06b0218e4e8db2b98845c3ec3e22e399c2.png)
