### ISSUE TITLE
Fix Missiles

### ISSUE THREAD

**Issue by LesPaul21** [NGGameSim/NGGameSim#90]
Issues to be fixed:
Headings are wrong
Indexing out of bounds issue
The missiles are calculating different headings but it is being represented as the same heading in SimViewer

**Comment by LesPaul21** [comment]
Headings are working better. Need to tweak for accuracy

**Comment by LesPaul21** [comment]
New issue: Headings that are being calculated are not even close to the headings being shown on the screen

**Comment by LesPaul21** [comment]
Headings are correct . Need to work with the fact that monogame defines y as down as opposed to up

**Comment by LesPaul21** [comment]
Corrections made to account for inverted monogame y axis. Need to fix translation a bit

**Comment by Moodiment** [comment]
missile out of bounds issue resolved now.
